### ISSUE TITLE
Unattended install

### ISSUE THREAD

**Issue by dansou901** [composer/windows-setup#50] opened 2016-03-15 10:36 UTC
Hi,
for now it is impossible to do an unattended install of composer. This would be necessary for deploying Composer through SCCM. To accomplish this, the installer needs to have a parameter on where to find php.exe. Is this possible to implement? Thanks in advance!
Regards,
dansou901

**Comment by johnstevenson** [comment] 2016-03-15 11:17
This will be addressed in a forthcoming release: Issue #51 
The beta exe there actually does silent installs/uninstalls but its quite raw:

- If php.exe is not in the path, then it will use the first one it finds. It looks in the system drive (usually C) for the following directories: ```\php*```, ```php\php*```, ```bin\php*```, ```bin\php\php*```. It then repeats the process for the User profile directory, then looks for specific (xampp, wamp, PhpEd) locations.
- Uninstall skips removing cache/config data for users

I plan to address this by having a `/PHP="path\to\php.exe"` and a `/PROXY="httpproxy"` flags for install, but I haven't worked out what I need for uninstall.

I don't know much about unattended installs for software deployment, so I could do with some guidance. For example, what account would such an install run it (an admin, a user or a system). If you could explain common use cases, we can try and come up with a solution.

**Comment by dansou901** [comment] 2016-03-15 13:20
For uninstall, I basically need an additional uninst.exe of some kind that just removes everything like the uninstall from system settings. This would take an argument like /VERYSILENT and /SUPPRESSMSGBOXES or similar. 
For the install I would suggest to introduce a variable in the installer for the PHP path, so that it can be set in a setup.inf to be loaded via /LOADINF. Then you can prepare a setup.inf while calling the installer with /SAVEINF=file.inf and later in the SCCM package use that file.inf in the /LOADINF parameter. 
For deploying we just have a line where we put the installer.exe and the command line arguments needed for the unattended install. For the uninstall there is another line. We can choose to install as system or as user, that is configurable. Nice would be a completely hidden install, so users installing this package just have to select it, go on install, wait a few seconds / minutes and it's there.

**Comment by johnstevenson** [comment] 2016-03-15 14:25
I'd appreciate it if you could explain a few things please.

> For uninstall, I basically need an additional uninst.exe
 
Additional? There is already an uninstaller in the install directory. Or you can get the location from the registry: `...Microsoft\Windows\CurrentVersion\Uninstall\{7315AF68-E777-496A-A6A2-4763A98ED35A}_isl`

> ...Then you can prepare a setup.inf while calling the installer with /SAVEINF=file.inf and later in the SCCM package use that file.inf in the /LOADINF parameter.
 
Why would ComposerSetup need to prepare a setup.inf? Surely that's the job of the program calling it. What values would you want in the saved file?

> We can choose to install as system or as user, that is configurable.

So which one would you use when deploying Composer? Are you intending to install it for all users or just a particular user

> Nice would be a completely hidden install, so users installing this package just have to select it, go on install, wait a few seconds / minutes and it's there.

Sorry, you've lost me now. I thought you wanted an unattended deployment, not users selecting to install it. If I have understood correctly.

**Comment by dansou901** [comment] 2016-03-15 14:36
1. Ok, just found the unins000.exe, that's the one I need. So that's solved.
2. By preparing the setup.inf I mean that I start the installer once with the SAVEINF parameter which creates the setup.inf with the values entered during the install. That way, I can be sure there are no typos in the setup.inf.
3. I would prefer to install it as system, for all users.
4. SCCM has a frontend for users of a managed system. In this frontend, the users can choose the software they need without admin rights and that frontend installs the software with admin rights. That way, the admins can choose which software is installable by the user.

**Comment by johnstevenson** [comment] 2016-03-15 14:54
> Ok, just found the unins000.exe, that's the one I need. So that's solved.

So when it uninstalls, do you want the user data to be removed (for all users)? It won't be able to remove any stuff from the Users path (like Composer\vendor\bin though).

> By preparing the setup.inf I mean that I start the installer once with the SAVEINF parameter...

So you basically want the params passed in the command line to be saved to a file names as per the /SAVEINF param. Why? You already know them (or will your front-end supply different values)?

> I would prefer to install it as system, for all users.

I'm not sure if this will work. The installer script looks for the user profile to write stuff to, which I imagine won't happen with a system account.

**Comment by dansou901** [comment] 2016-03-15 14:59
It's not necessary to remove the users data.
I want to use the SAVEINF mechanism to be sure to not include any mistakes in the setup.inf. It's not necessary, but nice to have.
I installed it with an admin account on my local system and could use it without problems with my normal user account. So I think it should work.

**Comment by johnstevenson** [comment] 2016-03-15 15:17
> It's not necessary to remove the users data.

Cool. The new (beta) uninstall ignores it anyway.

>I want to use the SAVEINF mechanism to be sure to not include any mistakes in the setup.inf. It's not necessary, but nice to have.

I still don't understand! Who writes the setup inf? Anyway, I'll think about incorporating both LOADINF and SAVEINF then I won't have to worry about your use-case!

> I installed it with an admin account on my local system and could use it without problems with my normal user account. So I think it should work.

Yes, if you install as a user with admin privileges then that is standard (if you're not running as an admin then the installer self-elevates via a UAC prompt). However, and here is my lack of understanding of unattended deploys, what happens when a central server rolls out an update to stuff - what account is being used then?

**Comment by dansou901** [comment] 2016-03-15 15:26
The setup inf gets written after calling the Composer-Setup.exe with /SAVEINF=setup.inf. That way, you can select the path to php.exe in the wizard, so you literally can't write a wrong path in the setup.inf. 
In our case, the application gets rolled out to the users, but uses a system admin account to install itself. So it's the same behaviour like installing the software as admin.

**Comment by johnstevenson** [comment] 2016-03-15 15:49
> The setup inf gets written after calling the Composer-Setup.exe with /SAVEINF=setup.inf. That way, you can select the path to php.exe in the wizard, 

Sorry, I'm lost again. The user will not be able to select the path to php.exe in the wizard. Its an unattended install.

**Comment by Seldaek** [comment] 2016-03-15 15:55
@johnstevenson I think you misunderstood :) They want to run the setup once with /SAVEINF=setup.inf, go through it interactively, then using that generated setup.inf run the same setup using /LOADINF=setup.inf on all the other machines they manage to do an unattended setup there.

The main benefit is that the setup outputs the inf file with this model, so you can't mess up or forget something. It's like a record/replay thing for the setup process.

**Comment by dansou901** [comment] 2016-03-15 15:56
^^ You got it, that's exactly what we want to do.

**Comment by johnstevenson** [comment] 2016-03-15 15:59
Aha, got it now!

**Comment by johnstevenson** [comment] 2016-03-16 18:07
Could you give this a run out, please. [Composer-Setup.4.0.2.exe beta](https://s3-eu-west-1.amazonaws.com/johnstevenson/composer/Composer-Setup.4.0.2.exe)
 Params are:

- `/PHP="path\to\php.exe"`
- `/PROXY="httpproxy"`
- `/SILENT` as per Inno documentation
- `/VERYSILENT` as per Inno documentation

It shouldn't need any others (like /SUPPRESSMSGBOXES). I'd appreciate it if you could chuck a few googlies at it, like a non-existent php file and a bad phpini (set allow_url_fopen to off) to make sure it behaves correctly.

All feedback gratefully received.

**Comment by dansou901** [comment] 2016-03-16 18:11
I'll test this tomorrow at work and will report back. I'm afraid that I don't have time to check with bad settings, but I'll be able to tell you if it works in SC CM.

**Comment by johnstevenson** [comment] 2016-03-16 18:17
Thanks, that would be great.

>  I'm afraid that I don't have time to check with bad settings

I could say that I didn't really have time to implement what you wanted - but that would probably be a bit churlish! So, pretty please?

**Comment by dansou901** [comment] 2016-03-16 18:43
I'm sorry, can the additional test wait for two weeks? I'll be in holidays from Saturday to beginning of April, that's why. I'll have to sort out other things at work until Friday. After the holidays, there will be time to test.

**Comment by dansou901** [comment] 2016-03-16 18:45
I can test it without SCCM, that OK?

**Comment by johnstevenson** [comment] 2016-03-16 18:52
Thanks (and sorry for sounding a bit arsey!). Any form of testing and feedback would be very much appreciated. Enjoy your hols.

**Comment by dansou901** [comment] 2016-03-16 18:54
No problem. Just waiting for windows updates to get installed, I don't use my windows installation at home, I'm usually using Linux...

**Comment by dansou901** [comment] 2016-03-16 19:45
Just tested your setup. Works as advertised. I'll use /VERYSILENT for SCCM to suppress the install progress window (see INNO docs). For wrong settings: I tested with a php.ini without enabled openssl extension -> Composer install won't do anything (just silently quits). Same behaviour for allow_url_fopen=Off. Suggestion: Prompt a message that cannot be suppressed by /VERYSILENT and /SUPPRESSMSGBOXES when install isn't successfull. Would be good for SCCM because otherwise users would have to rely on SCCM error messages, which aren't verbose enough. Great work though, thanks!

**Comment by dansou901** [comment] 2016-03-16 19:51
One thing though... PHP directory won't get recorded while using /SAVEINF. Can you add this? If not, that's also fine, but would be nice to have. I'll test it as soon as you provide, promise.

**Comment by johnstevenson** [comment] 2016-03-16 20:24
Hey thanks.

Re wrong settings:
The reason it quits is because Inno can't move onto the next page automatically in these error conditions.

In the case of  openssl not enabled, the user is shown the Security page where they need to confirm that they want to disable TLS, before the Next button becomes available. And in the case of allow_url_fopen=Off, they need to enable it in their php ini and click the Retry button (Inno will abort on the second retry).

It's very useful that you've tested this, because I've got the functionality wrong by trying to combine VERYSILENT and SUPPRESSMSGBOXES.

I think it would be better if I recognize SUPPRESSMSGBOXES. This would mean that the major "stop, you can't go any further" and "hey, you've got to do something" situations would show an error on your /VERYSILENT installs before aborting.

Does that sound like a plan?

**Comment by johnstevenson** [comment] 2016-03-16 20:28
Incidentally, in case it helps you, the setup is logged automatically now and is stored in the users temp directory `AppData\Local\Temp` as `Setup Log YYYY-MM-DD #nnn.txt`. The log is deleted
on reboot (Admin installs only).

**Comment by dansou901** [comment] 2016-03-16 20:31
Re SUPPRESSMSGBOXES: That would be a good idea.

**Comment by dansou901** [comment] 2016-03-16 20:41
For the logs: Good to know that they exist, so I can deploy todays version without fearing missing error descriptions.

**Comment by johnstevenson** [comment] 2016-03-16 21:36
[Composer-Setup.4.0.3.exe beta](https://s3-eu-west-1.amazonaws.com/johnstevenson/composer/Composer-Setup.4.0.3.exe) - incorporates correct /SUPPRESSMSGBOXES functionality. Otherwsie an error is shown when setup cannot continue without user-interaction.

I haven't forgotten about your PHP directory request, but it's time for a beer now.

**Comment by dansou901** [comment] 2016-03-16 21:40
That's fine, take your time. Cheers! Will test asap.

**Comment by dansou901** [comment] 2016-03-16 21:48
Ok, test results: Without /SUPPRESSMSGBOXES I get the error box, without I won't get it. Great work and thanks!

**Comment by johnstevenson** [comment] 2016-03-16 21:53
Good and thanks. I'm afraid it's a general rather than a specific error message, but I'm sure that's better than nothing.

**Comment by dansou901** [comment] 2016-03-16 21:54
It includes the correct path to the log file. That should be enough in most cases.

**Comment by johnstevenson** [comment] 2016-03-17 09:12
Re PHP directory:
I choose the `/PHP` param because I thought that was more logical, in terms of matching what you do interactively (ie select a specific php.exe). However before you do that, the installer will have searched the PATH and displayed any php.exe found as the default choice, so my logic doesn't look so hot.

I don't want to offer `/PHP` and `/PATH` options (too messy), so could you explain the reason why a `/PATH` param is better in your situation to help me make a decision.

**Comment by dansou901** [comment] 2016-03-17 10:27
The /PHP param itself is ok. The only addition I suggested was to write this param also in a file while doing SAVEINF, so a setup.inf has also an entry like PHP=/path/to/php.exe.

**Comment by johnstevenson** [comment] 2016-03-17 10:43
But it does this already. The SAVEINF file looks like:
```
[Setup]
Lang=default
Dir=C:\Program Files (x86)\ComposerSetup
Group=(Default)
NoIcons=0
Tasks=
[params]
php=C:\php\php.exe
proxy=
```

**Comment by dansou901** [comment] 2016-03-17 11:06
For me [params] won't get written in 4.0.3 beta.

**Comment by johnstevenson** [comment] 2016-03-17 11:33
Does it write anything at all - ie does it write the Setup section?

**Comment by dansou901** [comment] 2016-03-17 12:01
Yes, it does write the setup section, but no params section.

**Comment by johnstevenson** [comment] 2016-03-17 12:09
In which case the params section is probably getting written to a file somewhere else. Does your /SAVEINF param include a full path?

**Comment by dansou901** [comment] 2016-03-17 12:37
I didn't include the full path, just a relative one, but I can try again with a full path.

**Comment by dansou901** [comment] 2016-03-17 12:38
With a full path the params section does get written, so that's sorted.

**Comment by johnstevenson** [comment] 2016-03-17 12:46
Thanks, but that shouldn't really be necessary, so it is my mistake. This works with relative paths:[Composer-Setup.4.0.4.exe beta](https://s3-eu-west-1.amazonaws.com/johnstevenson/composer/Composer-Setup.4.0.4.exe)

**Comment by dansou901** [comment] 2016-03-17 14:40
Yeah, that works with relative paths. Thanks! Now I just need to deploy PHP via SCCM before creating a package for Composer, problem is there is no msi installer for PHP anymore...

**Comment by johnstevenson** [comment] 2016-03-24 13:11
This has all now been released in [v4.1.0](https://github.com/composer/windows-setup/releases/tag/v4.1.0). Thanks for all your help.

**Closed by johnstevenson** 2016-03-24 13:11 UTC

**Comment by imran9k** [comment] 2020-02-03 03:48
> @johnstevenson I think you misunderstood :) They want to run the setup once with /SAVEINF=setup.inf, go through it interactively, then using that generated setup.inf run the same setup using /LOADINF=setup.inf on all the other machines they manage to do an unattended setup there.
> 
> The main benefit is that the setup outputs the inf file with this model, so you can't mess up or forget something. It's like a record/replay thing for the setup process.

I am able to record inf file but when i trying run the inf file with composer setup.exe /LOADINF=setup.inf file still i am getting UI mode while deploying, Please suggest me how to make silently after generating inf file

**Comment by imran9k** [comment] 2020-02-03 03:50
> For uninstall, I basically need an additional uninst.exe of some kind that just removes everything like the uninstall from system settings. This would take an argument like /VERYSILENT and /SUPPRESSMSGBOXES or similar.
> For the install I would suggest to introduce a variable in the installer for the PHP path, so that it can be set in a setup.inf to be loaded via /LOADINF. Then you can prepare a setup.inf while calling the installer with /SAVEINF=file.inf and later in the SCCM package use that file.inf in the /LOADINF parameter.
> For deploying we just have a line where we put the installer.exe and the command line arguments needed for the unattended install. For the uninstall there is another line. We can choose to install as system or as user, that is configurable. Nice would be a completely hidden install, so users installing this package just have to select it, go on install, wait a few seconds / minutes and it's there.


I am able to record inf file but when i trying run the inf file with composer setup.exe /LOADINF=setup.inf file still i am getting UI mode while deploying, Please suggest me how to make silently after generating inf file

**Comment by johnstevenson** [comment] 2020-02-03 10:06
@imran9k The enable a silent installation, you need to add the required params on the command line (depending on how _silent_ you want it), as per the Inno Septup help: https://www.jrsoftware.org/ishelp/topic_setupcmdline.htm

Use `/VERYSILENT /SUPPRESSMSGBOXES /NORESTART` if you don't want to show any UI.

**Comment by imran9k** [comment] 2020-02-12 08:05
> @imran9k The enable a silent installation, you need to add the required params on the command line (depending on how _silent_ you want it), as per the Inno Septup help: https://www.jrsoftware.org/ishelp/topic_setupcmdline.htm
> 
> Use `/VERYSILENT /SUPPRESSMSGBOXES /NORESTART` if you don't want to show any UI.

**Comment by imran9k** [comment] 2020-02-12 08:15
Installation is fine, During uninstall , we are running uninstall.exe from C:\Programfiles(x86)\Composersetup\uninstall.exe" with the parameter /VERYSILENT , But uninstall is not happening we have waiting for hours in taskmanager uninstall.exe is keep on running.
We have checked in UI mode , uninstall.exe is launching uninstall wizard but it is not proceeding to finish button though we have waited for hours.

**Comment by johnstevenson** [comment] 2020-02-12 10:47
@imran9k That is unexpected behaviour. Could you run the uninstaller with the `/LOG` parameter. This will write a log file in the users temp directory, named something like `Uninstall Log 2020-02-12 #001.txt`  (alternatively you can use `/LOG="filename"` to write to a location of your choice).

We might be able to work out where it is getting stuck for this.
