### ISSUE TITLE
Issue Reinstalling composer

### ISSUE THREAD

**Issue by Alvinkariuki** [composer/windows-setup#113] opened 2020-01-30 11:51 UTC
I
![Capture](https://user-images.githubusercontent.com/24392707/73447924-ce9cc480-4370-11ea-9356-ea2e9e014797.PNG)
 installed composer for the first time, all the folders required were generated correctly. I uninstalled it, both Local and Roaming folders. When i reinstall it the same folders are not generated as before

**Comment by johnstevenson** [comment] 2020-02-04 11:01
@Alvinkariuki Did you use Composer-Setup.exe to install and uninstall this? If so you should have some log files in your temp directory, as described in this repo's new issue template: https://github.com/composer/windows-setup/issues/new

We need to be able to reproduce the specific actions you to took, in order to reproduce and investigate this issue.

**Comment by Alvinkariuki** [comment] 2020-02-05 07:36
[Setup Log 2020-01-30 #001.txt](https://github.com/composer/windows-setup/files/4158019/Setup.Log.2020-01-30.001.txt)
[Setup Log 2020-02-05 #001.txt](https://github.com/composer/windows-setup/files/4158020/Setup.Log.2020-02-05.001.txt)

**Comment by johnstevenson** [comment] 2020-02-06 12:10
Thanks. Looking at the log for your current installation, it would appear that you installed it **over** the earlier installation.

>  I uninstalled it, both Local and Roaming folders. When i reinstall it the same folders are not generated as before

So you did not use the uninstaller, but removed things manually. What exactly did you do (ie delete)?

Also, what is the output when you run:

-  `composer config --global cache-dir`
- `composer config --global home`

**Comment by Alvinkariuki** [comment] 2020-02-11 20:06
The uninstaller initially gave me the option to delete contents in both folders, Then i manually deleted them after uninstalling composer

I deleted both composer folders in the Roaming and Local directories

on running:

- composer config --global cache-dir
         C:/Users/me/AppData/Local/Composer

-composer config --global home
         C:/Users/me/AppData/Roaming/Composer

**Comment by johnstevenson** [comment] 2020-02-18 10:57
I've been unable to reproduce this. When the composer installer script runs it only creates the `AppData/Roaming/Composer` folder. The `AppData/Local/Composer` folder is created after you have run Composer.

So which folders are actually missing?

Could you please show the exact paths - because the results of the config commands both point to the `C:/Users/me/AppData` folder, whereas your original screenshot (and log files) show your user profile at `C:\Users\user\AppData`.

**Comment by johnstevenson** [comment] 2020-03-11 11:25
Closing, as no further information.

**Closed by johnstevenson** 2020-03-11 11:25 UTC
