### ISSUE TITLE
Composer ignores installation directory php file

### ISSUE THREAD

**Issue by tschallacka** [composer/windows-setup#42] opened 2015-06-22 08:41 UTC
When composer is installed it totally ignores which directory is supplied as php dir. It completely defaults to C:\php.
I have 4 php versions on my system and I need it to point to C:\php5.5.IIS for the php.exe and the ext directory, but it keeps looking into c:\php even though i select php5.5 directory in the installer

how do I resolve this? there doesn't seem to be a command line option and I can't modify the path variables. because other apps will crash then.

Warning: PHP Startup: bz2: Unable to initialize module
Module compiled with module API=20090626
PHP    compiled with module API=20121212
These options need to match
 in Unknown on line 0

Warning: PHP Startup: curl: Unable to initialize module
Module compiled with module API=20090626
PHP    compiled with module API=20121212
These options need to match
 in Unknown on line 0

Warning: PHP Startup: gd: Unable to initialize module
Module compiled with module API=20090626
PHP    compiled with module API=20121212
These options need to match
 in Unknown on line 0

Warning: PHP Startup: mbstring: Unable to initialize module
Module compiled with module API=20090626
PHP    compiled with module API=20121212
These options need to match
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'C:\PHP\ext\php_mcrypt.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: mysql: Unable to initialize module
Module compiled with module API=20090626
PHP    compiled with module API=20121212
These options need to match
 in Unknown on line 0

Warning: PHP Startup: openssl: Unable to initialize module
Module compiled with module API=20090626
PHP    compiled with module API=20121212
These options need to match
 in Unknown on line 0

Warning: PHP Startup: PDO: Unable to initialize module
Module compiled with module API=20060613
PHP    compiled with module API=20121212
These options need to match
 in Unknown on line 0

Warning: PHP Startup: pdo_mysql: Unable to initialize module
Module compiled with module API=20090626
PHP    compiled with module API=20121212
These options need to match
 in Unknown on line 0

Warning: PHP Startup: soap: Unable to initialize module
Module compiled with module API=20090626
PHP    compiled with module API=20121212
These options need to match
 in Unknown on line 0

Warning: PHP Startup: tidy: Unable to initialize module
Module compiled with module API=20090626
PHP    compiled with module API=20121212
These options need to match
 in Unknown on line 0

Warning: PHP Startup: zip: Unable to initialize module
Module compiled with module API=20060613
PHP    compiled with module API=20121212
These options need to match
 in Unknown on line 0

Warning: PHP Startup: eAccelerator: Unable to initialize module
Module compiled with module API=20060613
PHP    compiled with module API=20121212
These options need to match
 in Unknown on line 0

Warning: PHP Startup: memcache: Unable to initialize module
Module compiled with module API=20060613
PHP    compiled with module API=20121212
These options need to match
 in Unknown on line 0

Warning: PHP Startup: sqlsrv: Unable to initialize module
Module compiled with module API=20100525
PHP    compiled with module API=20121212
These options need to match
 in Unknown on line 0

Warning: PHP Startup: pdo_sqlsrv: Unable to initialize module
Module compiled with module API=20100525
PHP    compiled with module API=20121212
These options need to match
 in Unknown on line 0
3ECDC245-751A-4962-B580-B8A250EDD1CF5.5.23

2015-06-22 10:45:02.791   Log opened. (Time zone: UTC+02:00)
2015-06-22 10:45:02.791   Setup version: Inno Setup version 5.5.4 (u)
2015-06-22 10:45:02.791   Original Setup EXE: C:\Users\user\Desktop\Composer-Setup.exe
2015-06-22 10:45:02.791   Setup command line: /SL5="$1E01F4,220038,119296,C:\Users\user\Desktop\Composer-Setup.exe" /SPAWNWND=$11028E /NOTIFYWND=$A0232 /log="log.txt"
2015-06-22 10:45:02.791   Windows version: 6.1.7601 SP1  (NT platform: Yes)
2015-06-22 10:45:02.791   64-bit Windows: Yes
2015-06-22 10:45:02.791   Processor architecture: x64
2015-06-22 10:45:02.791   User privileges: Administrative
2015-06-22 10:45:02.791   64-bit install mode: No
2015-06-22 10:45:02.791   Created temporary directory: C:\Users\USER~1\AppData\Local\Temp\is-F8LPT.tmp
2015-06-22 10:45:02.806   Extracting temporary file: C:\Users\USER~1\AppData\Local\Temp\is-F8LPT.tmp\composer
2015-06-22 10:45:02.822   Extracting temporary file: C:\Users\USER~1\AppData\Local\Temp\is-F8LPT.tmp\setup.class.php
2015-06-22 10:45:02.822   Extracting temporary file: C:\Users\USER~1\AppData\Local\Temp\is-F8LPT.tmp\setup.php
2015-06-22 10:45:02.822   DEBUG:: Getting path info from registry
2015-06-22 10:45:04.397   DEBUG:: User selected Shell Menus: Do not install
2015-06-22 10:45:04.819   DEBUG:: Checking php: C:\PHP5.3.17\php.exe
2015-06-22 10:45:08.360   DEBUG:: Calling cmd.exe with params: /c "C:\PHP5.3.17\php.exe setup.php -- --php > C:\Users\USER~1\AppData\Local\Temp\is-F8LPT.tmp\result.txt"
2015-06-22 10:45:11.402   PHPDBG:: 5.3.17
2015-06-22 10:45:11.402   DEBUG:: Checking paths
2015-06-22 10:45:11.417   DEBUG:: Checking php path
2015-06-22 10:45:11.417   DEBUG:: Checking for composer bin path
2015-06-22 10:45:11.417   DEBUG:: Checking PathExt values
2015-06-22 10:45:17.626   DEBUG:: Checking php: C:\PHP5.5.IIS\php.exe
2015-06-22 10:45:19.311   DEBUG:: Calling cmd.exe with params: /c "C:\PHP5.5.IIS\php.exe setup.php -- --php > C:\Users\USER~1\AppData\Local\Temp\is-F8LPT.tmp\result.txt"
2015-06-22 10:45:20.231   DEBUG:: Checking php: error [ERR_INVALID]
2015-06-22 10:45:23.492   Deinitializing Setup.
2015-06-22 10:45:23.492   DEBUG:: Setup cancelled or aborted
2015-06-22 10:45:23.492   Log closed.

2015-06-22 10:43:41.468   Log opened. (Time zone: UTC+02:00)
2015-06-22 10:43:41.468   Setup version: Inno Setup version 5.5.4 (u)
2015-06-22 10:43:41.468   Original Setup EXE: C:\Users\user\Desktop\Composer-Setup.exe
2015-06-22 10:43:41.468   Setup command line: /SL5="$E0382,220038,119296,C:\Users\user\Desktop\Composer-Setup.exe" /SPAWNWND=$1003E2 /NOTIFYWND=$140242 /log "log.txt"
2015-06-22 10:43:41.468   Windows version: 6.1.7601 SP1  (NT platform: Yes)
2015-06-22 10:43:41.468   64-bit Windows: Yes
2015-06-22 10:43:41.468   Processor architecture: x64
2015-06-22 10:43:41.468   User privileges: Administrative
2015-06-22 10:43:41.483   64-bit install mode: No
2015-06-22 10:43:41.483   Created temporary directory: C:\Users\USER~1\AppData\Local\Temp\is-1S2EM.tmp
2015-06-22 10:43:41.483   Extracting temporary file: C:\Users\USER~1\AppData\Local\Temp\is-1S2EM.tmp\composer
2015-06-22 10:43:41.514   Extracting temporary file: C:\Users\USER~1\AppData\Local\Temp\is-1S2EM.tmp\setup.class.php
2015-06-22 10:43:41.514   Extracting temporary file: C:\Users\USER~1\AppData\Local\Temp\is-1S2EM.tmp\setup.php
2015-06-22 10:43:41.514   DEBUG:: Getting path info from registry
2015-06-22 10:43:44.026   DEBUG:: User selected Shell Menus: Do not install
2015-06-22 10:43:44.681   DEBUG:: Checking php: C:\PHP5.3.17\php.exe
2015-06-22 10:43:49.502   DEBUG:: Calling cmd.exe with params: /c "C:\PHP5.3.17\php.exe setup.php -- --php > C:\Users\USER~1\AppData\Local\Temp\is-1S2EM.tmp\result.txt"
2015-06-22 10:43:54.244   PHPDBG:: 5.3.17
2015-06-22 10:43:54.244   DEBUG:: Checking paths
2015-06-22 10:43:54.244   DEBUG:: Checking php path
2015-06-22 10:43:54.244   DEBUG:: Checking for composer bin path
2015-06-22 10:43:54.244   DEBUG:: Checking PathExt values
2015-06-22 10:43:58.674   Message box (Yes/No):
                          Setup is not complete. If you exit now, the program will not be installed.
                          
                          You may run Setup again at another time to complete the installation.
                          
                          Exit Setup?
2015-06-22 10:44:00.749   User chose No.
2015-06-22 10:44:01.342   DEBUG:: Downloading from getcomposer.org
2015-06-22 10:44:01.342   DEBUG:: Calling cmd.exe with params: /c "C:\PHP5.3.17\php.exe setup.php -- --download > C:\Users\USER~1\AppData\Local\Temp\is-1S2EM.tmp\result.txt"
2015-06-22 10:44:09.610   DEBUG:: Running PrepareToInstall tasks
2015-06-22 10:44:09.610   DEBUG:: Writing Unix line-endings to C:\Users\USER~1\AppData\Local\Temp\is-1S2EM.tmp\composer
2015-06-22 10:44:09.626   Starting the installation process.
2015-06-22 10:44:09.626   Setting permissions on directory: C:\ProgramData\ComposerSetup\bin
2015-06-22 10:44:09.626   Directory for uninstall files: C:\Program Files (x86)\ComposerSetup
2015-06-22 10:44:09.626   Will append to existing uninstall log: C:\Program Files (x86)\ComposerSetup\unins000.dat
2015-06-22 10:44:09.626   -- File entry --
2015-06-22 10:44:09.626   Dest filename: C:\Program Files (x86)\ComposerSetup\unins000.exe
2015-06-22 10:44:09.626   Time stamp of our file: 2015-06-22 10:43:41.421
2015-06-22 10:44:09.626   Dest file exists.
2015-06-22 10:44:09.626   Time stamp of existing file: 2015-06-22 10:15:59.331
2015-06-22 10:44:09.626   Version of our file: 51.1052.0.0
2015-06-22 10:44:09.626   Version of existing file: 51.1052.0.0
2015-06-22 10:44:09.626   Installing the file.
2015-06-22 10:44:09.641   Uninstaller requires administrator: Yes
2015-06-22 10:44:09.641   Leaving temporary file in place for now.
2015-06-22 10:44:09.641   -- File entry --
2015-06-22 10:44:09.641   Dest filename: C:\Program Files (x86)\ComposerSetup\userdata.dll
2015-06-22 10:44:09.641   Time stamp of our file: 2013-11-22 16:10:20.000
2015-06-22 10:44:09.641   Dest file exists.
2015-06-22 10:44:09.641   Time stamp of existing file: 2013-11-22 16:10:20.000
2015-06-22 10:44:09.641   Installing the file.
2015-06-22 10:44:09.641   Successfully installed the file.
2015-06-22 10:44:09.641   -- File entry --
2015-06-22 10:44:09.641   Dest filename: C:\Program Files (x86)\ComposerSetup\unins.ico
2015-06-22 10:44:09.641   Time stamp of our file: 2013-11-21 13:59:36.000
2015-06-22 10:44:09.641   Dest file exists.
2015-06-22 10:44:09.641   Time stamp of existing file: 2013-11-21 13:59:36.000
2015-06-22 10:44:09.641   Installing the file.
2015-06-22 10:44:09.641   Successfully installed the file.
2015-06-22 10:44:09.641   -- File entry --
2015-06-22 10:44:09.641   Dest filename: C:\Program Files (x86)\ComposerSetup\Composer-Setup.exe
2015-06-22 10:44:09.641   Time stamp of our file: 2015-06-22 10:15:45.097
2015-06-22 10:44:09.641   Dest file exists.
2015-06-22 10:44:09.641   Time stamp of existing file: 2015-06-22 10:15:45.097
2015-06-22 10:44:09.641   Installing the file.
2015-06-22 10:44:09.657   Successfully installed the file.
2015-06-22 10:44:09.657   -- File entry --
2015-06-22 10:44:09.657   Dest filename: C:\ProgramData\ComposerSetup\bin\composer.bat
2015-06-22 10:44:09.657   Time stamp of our file: 2013-10-16 18:21:40.000
2015-06-22 10:44:09.657   Dest file exists.
2015-06-22 10:44:09.657   Time stamp of existing file: 2013-10-16 18:21:40.000
2015-06-22 10:44:09.657   Installing the file.
2015-06-22 10:44:09.672   Successfully installed the file.
2015-06-22 10:44:09.672   -- File entry --
2015-06-22 10:44:09.672   Dest filename: C:\ProgramData\ComposerSetup\bin\composer
2015-06-22 10:44:09.672   Time stamp of our file: 2015-06-22 10:44:09.610
2015-06-22 10:44:09.672   Dest file exists.
2015-06-22 10:44:09.672   Time stamp of existing file: 2015-06-22 10:17:27.004
2015-06-22 10:44:09.672   Installing the file.
2015-06-22 10:44:09.672   Successfully installed the file.
2015-06-22 10:44:09.672   -- File entry --
2015-06-22 10:44:09.672   Dest filename: C:\ProgramData\ComposerSetup\bin\composer.phar
2015-06-22 10:44:09.672   Time stamp of our file: 2015-06-22 10:44:09.594
2015-06-22 10:44:09.672   Dest file exists.
2015-06-22 10:44:09.672   Time stamp of existing file: 2015-06-22 10:17:26.988
2015-06-22 10:44:09.672   Installing the file.
2015-06-22 10:44:09.672   Successfully installed the file.
2015-06-22 10:44:09.766   Installation process succeeded.
2015-06-22 10:44:09.766   Need to restart Windows? No
2015-06-22 10:44:13.073   Deinitializing Setup.
2015-06-22 10:44:13.089   Log closed.

**Comment by Seldaek** [comment] 2015-06-22 16:59
I think you can perhaps fix it by adding the absolute path to the correct php.exe inside the composer.bat that the setup created. Otherwise it'll probably default on whichever php.exe it finds in the path..

**Comment by johnstevenson** [comment] 2015-06-22 17:28
@tschallacka From the logs it looks like the installer works fine for ```C:\PHP5.3.17\php.exe``` but fails when you try with ```C:\PHP5.5.IIS\php.exe```. 

The error message ```[ERR_INVALID]``` means that php hasn't run for some reason. Take a look at https://github.com/composer/composer/issues/3324

Could it be a problem with multiple php inis and the extension_dir entry, because whatever php version you are trying to run is looking in ```C:\PHP\ext\php_mcrypt.dll``` for its modules.

**Comment by curry684** [comment] 2016-02-12 10:28
The `ERR_INVALID` is in this case caused by the sparse output from the startup errors as shown at the top of his log. Means this is a duplicate of #36

**Comment by johnstevenson** [comment] 2016-03-24 12:41
This has been fixed in [v4.1.0](https://github.com/composer/windows-setup/releases/tag/v4.1.0), which recognizes common PHP config errors and displays all output.

**Closed by johnstevenson** 2016-03-24 12:41 UTC

**Comment by Jeeva-Rathinam** [comment] 2017-10-26 10:49
Anyone pls help me how can i solve this issue,

The PHP exe file you specified did not run correctly:
C:\wamp\bin\php\php7.0.25\php.exe

```
The php.ini used by your command-line PHP is: C:\wamp\bin\php\php7.0.25\php.ini

Program Output:
Warning: PHP Startup: mysql: Unable to initialize module
Module compiled with module API=20121212
PHP    compiled with module API=20151012
These options need to match
 in Unknown on line 0
```

**Comment by johnstevenson** [comment] 2017-10-26 12:40
The mysql extension was removed in PHP 7. You need to comment out the mysql entry in your ini file ans uncomment the mysqli one:

```
;extension=php_mysql.dll
extension=php_mysqli.dll
```
